markdown: kramdown
gems:
 - jekyll-paginate
 - jekyll-gist
 - jekyll-redirect-from

# Build settings
paginate: 10
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
